# Generated by Django 4.0.6 on 2022-08-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.IntegerField(primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
