# Generated by Django 4.0.6 on 2022-08-07 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_hostelite_delete_hostelites'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelite',
            name='enroll_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostelite',
            name='year',
            field=models.CharField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, max_length=10),
        ),
    ]
