# Generated by Django 4.0.6 on 2022-08-09 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0003_hostelite_enroll_date_alter_hostelite_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelite',
            name='branch',
            field=models.CharField(choices=[('CS', 'CSE'), ('E', 'ECE'), ('EE', 'EEE'), ('EI', 'EIE')], default='CS', max_length=5),
        ),
        migrations.AddField(
            model_name='hostelite',
            name='home',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('hobby', models.CharField(max_length=100)),
                ('sic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc', models.BooleanField(default=False)),
                ('dc', models.BooleanField(default=False)),
                ('sic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
