# Generated by Django 4.0.6 on 2022-08-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_hostelite_branch_hostelite_home_register_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelite',
            name='year',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022),
        ),
    ]
