# Generated by Django 4.0.6 on 2022-08-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_alter_hostelite_sic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelite',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='hostelite',
            name='email',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelite',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
