# Generated by Django 4.0.6 on 2022-08-26 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        ('hostel', '0007_rename_name_hostelite_first_name_hostelite_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('later', models.IntegerField()),
                ('status1', models.BooleanField(default=False)),
                ('status2', models.BooleanField(default=False)),
                ('sic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.register')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomate1', models.IntegerField()),
                ('roomate2', models.IntegerField()),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
